env:
  browser: true
  es6: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: 12
rules:
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  no-unused-vars:
    - error
    - args: none
  quotes:
    - error
    - single
  semi:
    - error
    - always
